const posts = [

    /* ── NEW 6 ── */
    {
        slug: 'mahr-dower-rights-wife-bangladesh',
        bnSlug: 'mahr-den-mohor-odhikar-bangladesh',
        title: "Wife's Rights to Mahr (Dower) in Bangladesh: What the Law Says",
        category: 'Family Law',
        readTime: '6 min read',
        metaTitle: "Mahr (Dower) Rights of Wife in Bangladesh – Complete Legal Guide",
        metaDescription: "What is mahr (dower) in Bangladesh? When is it payable, how much can a wife claim, and what happens if the husband refuses? Expert family lawyer guide.",
        keywords: ['mahr Bangladesh', 'dower rights Bangladesh', 'den mohor Bangladesh', 'wife mahr claim Bangladesh', 'divorce mahr Bangladesh', 'family lawyer Dhaka'],
        publishedDate: '2026-03-24',
        heroIntro: "Mahr (also spelled mehr or dower) is a mandatory gift from husband to wife in Islamic marriage law and is a legally enforceable right in Bangladesh. Understanding when it is due, how much it should be, and how to claim it is essential for any Muslim woman.",
        toc: ['What is Mahr (Dower) in Bangladesh?', 'Types of Mahr: Prompt and Deferred', 'How the Mahr Amount is Determined', 'When is Mahr Payable?', 'How to Claim Unpaid Mahr', 'Mahr in Divorce and Khula'],
        sections: [
            { h2: 'What is Mahr (Dower) in Bangladesh?', content: `<p><strong>Mahr</strong> (or dower) is a mandatory payment or gift given by a husband to his wife under Muslim personal law, as recorded in the <strong>Kabinnama</strong> (marriage registration certificate). Under the <strong>Muslim Family Laws Ordinance 1961</strong> and the Dissolution of Muslim Marriages Act 1939, mahr is a legal right — not a gift that the husband can choose to give or withhold. The wife can sue to recover it in the Family Court.</p><p>If the Kabinnama does not specify a mahr amount, "proper dower" (mahr-e-misl) applies — determined by customary standards based on the wife's family status, father's social position, and locality.</p>` },
            { h2: 'Types of Mahr: Prompt and Deferred', content: `<p>Mahr is typically divided into two parts in the Kabinnama:</p><ul><li><strong>Prompt Mahr (Mahr-e-Mu'ajjal)</strong>: Payable immediately on marriage, on demand, or at a specified time. If not paid, the wife can refuse to cohabit without forfeiting her rights.</li><li><strong>Deferred Mahr (Mahr-e-Mu'ajjal)</strong>: Payable on dissolution of marriage (by divorce or death of husband). If the husband dies without paying, the deferred mahr is a debt of the estate — payable before inheritance distribution.</li></ul>` },
            { h2: 'When is Mahr Payable?', content: `<p>Mahr becomes immediately enforceable:</p><ul><li>On husband's demand from wife for cohabitation (prompt mahr must be paid on demand)</li><li>On divorce — both prompt and deferred mahr become immediately due unless waived by khula</li><li>On death of the husband — deferred mahr is treated as a debt of the estate</li></ul><p>A wife is entitled to refuse conjugal rights until prompt mahr is paid, without it affecting her own maintenance rights.</p>` },
            { h2: 'How to Claim Unpaid Mahr', content: `<p>An unpaid mahr can be sued for in the <strong>Family Court</strong> under the Family Courts Ordinance 1985. File a plaint for recovery of mahr, attaching a certified copy of the Kabinnama. The court will examine the Kabinnama, determine the amount due, and pass a money decree against the husband. The decree can be enforced through attachment of his salary, bank account, or property.</p><p>Contact a <a href="/services/divorce-lawyer" style="color:var(--accent)">family lawyer in Uttara</a> for help filing a mahr recovery case.</p>` },
            { h2: 'Mahr in Divorce and Khula', content: `<p>On divorce initiated by the husband (talaq), the wife retains the full right to both prompt and deferred mahr. She cannot be forced to waive it as a condition of divorce.</p><p>However, in <strong>khula</strong> (wife-initiated divorce), the wife typically waives the deferred mahr or returns the prompt mahr as consideration for the husband's agreement. Courts will not force the husband into khula — his agreement is needed unless the wife seeks judicial khula through Family Court on valid grounds.</p><p><a href="/" style="color:var(--accent)">Advocate Md. Shah Alam</a> in Uttara handles all mahr and family law disputes.</p>` },
        ],
        faqs: [
            { question: 'Can a wife be forced to give up her mahr?', answer: 'No. Mahr is an absolute right. A husband cannot legally compel a wife to waive it as a condition of divorce. Any such agreement signed under duress is voidable.' },
            { question: 'What if the mahr amount in the Kabinnama is very low?', answer: '"Proper dower" (mahr-e-misl) provides a minimum benchmark. If the specified amount is unconscionably low, a court may still apply mahr-e-misl standards in certain circumstances — consult a lawyer.' },
            { question: 'Is mahr taxable in Bangladesh?', answer: 'Generally no. Mahr is treated as a personal right/gift under family law, not as income. However, large mahr transactions should be documented carefully.' },
            { question: 'Can mahr be claimed after the death of the husband?', answer: 'Yes. Deferred mahr is a debt of the estate and must be paid from the deceased husband\'s assets before the remaining estate is distributed among heirs.' },
        ],
        relatedServiceLinks: [
            { text: 'Divorce & Family Lawyer', to: '/services/divorce-lawyer' },
            { text: 'Criminal Lawyer Uttara', to: '/services/criminal-lawyer' },
        ],
    },

    /* ── NEW 7 ── */
    {
        slug: 'quash-false-case-bangladesh',
        bnSlug: 'mittha-mamla-kharej-bangladesh',
        title: 'How to Get a False Criminal Case Quashed in Bangladesh',
        category: 'Criminal Law',
        readTime: '7 min read',
        metaTitle: 'How to Quash a False Criminal Case in Bangladesh – Legal Guide',
        metaDescription: 'Facing a false FIR or fabricated criminal case in Bangladesh? Learn how to get a case quashed in the High Court Division — grounds, process, timeline, and costs.',
        keywords: ['quash false case Bangladesh', 'FIR quashing Bangladesh', 'High Court quash Bangladesh', 'false criminal case Bangladesh', 'criminal lawyer Dhaka'],
        publishedDate: '2026-03-24',
        heroIntro: 'Fabricated criminal cases are used as tools of harassment in Bangladesh — often arising from family disputes, business rivalries, or political vendettas. The High Court Division has the power to quash (cancel) an FIR or criminal proceeding where the case is manifestly false or an abuse of process.',
        toc: ['What Does "Quashing" a Case Mean?', 'Grounds for Quashing in Bangladesh', 'Where to File: High Court Division', 'The Quashing Process Step by Step', 'Stay of Proceedings During Quashing', 'What Happens After Quashing?'],
        sections: [
            { h2: 'What Does "Quashing" a Case Mean?', content: `<p>Quashing is a High Court order cancelling a criminal proceeding — typically an FIR, charge sheet, or the entire case. Once quashed, the case is legally dead — no arrest can be made on that FIR, no trial can proceed, and acquittal is not even required. A <a href="/services/criminal-lawyer" style="color:var(--accent)">criminal lawyer</a> files a writ petition or criminal miscellaneous case in the High Court Division under its inherent powers (Section 561A CrPC) or under Article 102 of the Constitution.</p>` },
            { h2: 'Grounds for Quashing in Bangladesh', content: `<p>The High Court will quash a case on these grounds:</p><ul><li>The allegations in the FIR, even if taken at face value, do not constitute any criminal offence</li><li>The FIR is manifestly attended with mala fide intent (filed for harassment, not for seeking justice)</li><li>The case is barred by limitation</li><li>There is no legal evidence — the case rests entirely on interested witnesses' bare statements</li><li>The matter is purely civil in nature dressed up as a criminal complaint</li><li>Continued prosecution would be an abuse of the court process</li><li>The parties have reached a genuine compromise (especially in compoundable offences)</li></ul>` },
            { h2: 'The Quashing Process Step by Step', content: `<ol><li>Engage a Supreme Court/criminal lawyer to analyse the FIR and build the quashing application.</li><li>File a <strong>Criminal Miscellaneous Case</strong> (Crl. Misc.) in the High Court Division under Section 561A CrPC, supported by an affidavit and relevant documents.</li><li>The court may issue a Rule Nisi (show cause) and a Stay of Proceedings — pausing the trial court case while the High Court considers the matter.</li><li>The State (government) files an affidavit-in-opposition.</li><li>Both sides are heard and the High Court passes judgment — either making the Rule absolute (quashing the case) or discharging it.</li></ol><p>Contact a <a href="/services/supreme-court-lawyer" style="color:var(--accent)">Supreme Court lawyer in Bangladesh</a> immediately if you are facing a false case.</p>` },
            { h2: 'Stay of Proceedings During Quashing', content: `<p>One of the key strategic advantages of filing a quashing petition is securing a <strong>Stay of Proceedings</strong> order that pauses the trial court case below. This prevents the complainant from getting an arrest warrant or pushing the case to trial while you wait for the High Court ruling. Your lawyer will apply for interim stay simultaneously with the quashing application.</p>` },
        ],
        faqs: [
            { question: 'How long does a quashing case take in Bangladesh?', answer: 'Cases where a stay is granted can take 6 months to 2 years to be fully decided. Urgent cases with clear merit may be resolved faster. The interim stay protects you during this period.' },
            { question: 'Can a case be quashed at the trial court level?', answer: 'No. Quashing jurisdiction lies exclusively with the High Court Division. Trial courts can discharge accused, but cannot quash an FIR.' },
            { question: 'What is the difference between discharge and quashing?', answer: 'Discharge happens at trial court level after charge framing — the accused is released. Quashing happens in the High Court and kills the proceeding before trial even begins. Quashing is more comprehensive.' },
            { question: 'Can a non-compoundable offence be quashed?', answer: 'Generally no, but the High Court has discretion where it finds the case to be an abuse of process, even for serious offences. Each case depends on its specific facts.' },
        ],
        relatedServiceLinks: [
            { text: 'Criminal Lawyer Uttara', to: '/services/criminal-lawyer' },
            { text: 'Supreme Court Lawyer', to: '/services/supreme-court-lawyer' },
            { text: 'Bail Lawyer Dhaka', to: '/services/bail-lawyer' },
        ],
    },

    /* ── NEW 8 ── */
    {
        slug: 'hire-cyber-crime-lawyer-bangladesh',
        bnSlug: 'cyber-crime-lawyer-neben-bangladesh',
        title: 'Cyber Crime Lawyer in Bangladesh: How to Get Legal Help',
        category: 'Cyber Law',
        readTime: '7 min read',
        metaTitle: 'Cyber Crime Lawyer in Bangladesh – Digital Security Act Defence 2025',
        metaDescription: 'Charged under the Digital Security Act or Cyber Security Act in Bangladesh? Learn how a cyber crime lawyer can help — DSA cases, online defamation, hacking, and financial fraud.',
        keywords: ['cyber crime lawyer Bangladesh', 'Digital Security Act Bangladesh', 'DSA case Bangladesh', 'cyber lawyer Dhaka', 'online defamation Bangladesh', 'Cyber Security Act Bangladesh'],
        publishedDate: '2026-03-24',
        heroIntro: 'Bangladesh has enacted strict cyber crime legislation — the Digital Security Act 2018 (DSA) and Cyber Security Act 2023 (CSA). Cases under these laws carry severe penalties including years of imprisonment. If you face a cyber crime charge or are a victim, hiring an experienced cyber crime lawyer is critical.',
        toc: ['Cyber Crime Laws in Bangladesh', 'Common Cyber Crime Cases', 'Penalties Under the Digital Security Act', 'What a Cyber Crime Lawyer Does', 'Steps to Take If Accused of a Cyber Crime', 'How Victims Can File Cyber Crime Cases'],
        sections: [
            { h2: 'Cyber Crime Laws in Bangladesh', content: `<p>Bangladesh cyber crime prosecution primarily relies on:</p><ul><li><strong>Cyber Security Act 2023 (CSA)</strong>: Replaced parts of the DSA 2018. Covers hacking, identity theft, unauthorised access, online fraud, and provocative digital content.</li><li><strong>Digital Security Act 2018 (DSA)</strong>: Still active for offences committed before the CSA. Widely criticised for wide-ranging provisions criminalising digital content.</li><li><strong>Information and Communication Technology (ICT) Act 2006</strong> (as amended): Earlier law, particularly Section 57, under which many older cases were filed.</li><li><strong>Penal Code 1860</strong>: Financial fraud, cheating, and forgery offences committed digitally are often charged under the Penal Code as well.</li></ul><p>Contact a <a href="/services/criminal-lawyer" style="color:var(--accent)">criminal lawyer in Dhaka</a> immediately if a case is filed against you under any of these laws.</p>` },
            { h2: 'Penalties Under the Digital Security Act', content: `<p>DSA/CSA penalties are severe:</p><ul><li>Hacking or unauthorised access: Up to 7–14 years imprisonment</li><li>Propagating offensive/false information: 3–10 years + fine</li><li>Identity theft: Up to 5 years</li><li>Online sexual harassment/defamation: Up to 5–7 years</li><li>Critical information infrastructure attack: Up to 14 years or life</li></ul><p>Many offences under the DSA are non-bailable, meaning the accused can be held in custody pending trial. Immediate bail application through the <a href="/services/bail-lawyer" style="color:var(--accent)">High Court</a> is often necessary.</p>` },
            { h2: 'What a Cyber Crime Lawyer Does', content: `<p>An experienced cyber crime lawyer in Bangladesh will:</p><ul><li>Analyse the FIR/complaint and assess defences available under DSA/CSA</li><li>Apply for bail immediately — DSA cases are notorious for lengthy pre-trial detention</li><li>Challenge the technical evidence (metadata, IP addresses, digital forensics reports)</li><li>File writ petitions to quash cases that are politically motivated or factually baseless</li><li>Negotiate with the complainant for settlement in compoundable cases</li><li>Defend at trial in the Cyber Tribunal</li></ul>` },
            { h2: 'Steps to Take If Accused of a Cyber Crime', content: `<ol><li><strong>Do not make any statement</strong> to police or cyber tribunal investigators without legal advice.</li><li><strong>Preserve all evidence</strong> including screenshots, messages, posts — both the allegedly offending content and any evidence of your innocence or intent.</li><li><strong>Hire a cyber crime lawyer immediately</strong> — even before arrest, if you hear a case is being filed.</li><li><strong>Apply for anticipatory bail</strong> if arrest is imminent.</li><li><strong>Document your alibi</strong> and gather witnesses who can attest to your whereabouts or account credentials security.</li></ol><p><a href="/" style="color:var(--accent)">Advocate Md. Shah Alam</a> in Uttara handles DSA/CSA defence cases in Dhaka.</p>` },
            { h2: 'How Victims Can File Cyber Crime Cases', content: `<p>If you are a victim of online fraud, hacking, defamation, or harassment in Bangladesh:</p><ul><li>File an FIR at your local police station or the <strong>Cyber Crime Investigation Department (CCID)</strong> of Bangladesh Police (Agargaon, Dhaka).</li><li>CCID has a dedicated online complaint portal at <strong>cybercrime.gov.bd</strong>.</li><li>Preserve all evidence: screenshots, URLs, chat logs, transaction records with timestamps.</li><li>A lawyer can help you draft a stronger complaint that accurately identifies the legal provisions violated and ensures evidence is collected in an admissible form.</li></ul>` },
        ],
        faqs: [
            { question: 'Is a cyber crime case bailable in Bangladesh?', answer: 'Most DSA/CSA offences are non-bailable, meaning police cannot grant bail — it must be sought from a court (Sessions Court or High Court). Immediate legal representation is essential to apply for bail.' },
            { question: 'What court hears cyber crime cases in Bangladesh?', answer: 'Cyber crime cases are heard in designated Cyber Tribunals established under the ICT Act and DSA. There are Cyber Tribunals in Dhaka and other divisional cities.' },
            { question: 'Can a defamatory Facebook post result in a DSA case in Bangladesh?', answer: 'Yes. Section 29 of the DSA (defamation) has been frequently used to file cases over social media posts. If you are accused under this provision, bail and quashing proceedings may be available.' },
            { question: 'Can someone file a DSA case against me anonymously?', answer: 'Yes. Complaints can be filed at police stations or online. However, in court proceedings, the complainant must be identified and can be cross-examined.' },
        ],
        relatedServiceLinks: [
            { text: 'Criminal Lawyer Uttara', to: '/services/criminal-lawyer' },
            { text: 'Bail Lawyer Dhaka', to: '/services/bail-lawyer' },
            { text: 'Supreme Court Lawyer', to: '/services/supreme-court-lawyer' },
        ],
    },

    /* ── NEW 9 ── */
    {
        slug: 'bail-cost-criminal-case-bangladesh',
        bnSlug: 'jamin-khoroch-bangladesh',
        title: 'How Much Does Bail Cost in a Criminal Case in Bangladesh?',
        category: 'Criminal Law',
        readTime: '6 min read',
        metaTitle: 'Bail Cost in Bangladesh Criminal Cases – Fees, Processes & Tips',
        metaDescription: 'What is the real cost of getting bail in Bangladesh? Lawyer fees, court fees, bail bond amounts, and what affects bail costs in Dhaka criminal cases — explained by a bail lawyer.',
        keywords: ['bail cost Bangladesh', 'bail fees Bangladesh', 'how much bail costs Dhaka', 'bail lawyer fees Bangladesh', 'bail bond Bangladesh'],
        publishedDate: '2026-03-24',
        heroIntro: 'When someone is arrested in Bangladesh, the first question from the family is: "How much will bail cost?" The answer depends on the type of offence, the court level, the strength of the case, and who you hire as your lawyer. This guide breaks it all down.',
        toc: ['Court Fees for a Bail Application', 'Bail Bond Amount: What the Court Sets', 'Lawyer Fees for Bail in Bangladesh', 'Factors That Affect Bail Cost', 'High Court Bail vs Magistrate Court Bail Costs'],
        sections: [
            { h2: 'Court Fees for a Bail Application', content: `<p>The actual court fees for filing a bail petition in Bangladesh are very low:</p><ul><li><strong>Magistrate Court bail application</strong>: BDT 50–200 in process/stamp fees</li><li><strong>Sessions Court bail</strong>: BDT 100–500</li><li><strong>High Court Division bail application</strong>: BDT 200–600 in court fees, plus affidavit stamps</li></ul><p>The main cost of bail is always the <strong>lawyer's professional fee</strong>, not the government court fee. The two are entirely separate.</p>` },
            { h2: 'Bail Bond Amount: What the Court Sets', content: `<p>The court sets a bail bond (surety) amount that the accused or a guarantor must provide. This is security — not a payment to the court. If the accused absconds, the bond amount is forfeited. The bond is returned when the case concludes. Bond amounts vary:</p><ul><li><strong>Bailable offences (Magistrate)</strong>: BDT 5,000 – BDT 1,00,000</li><li><strong>Non-bailable offences (Sessions)</strong>: BDT 50,000 – BDT 5,00,000+</li><li><strong>High Court bail in serious cases</strong>: BDT 5,00,000 – BDT 50,00,000+ depending on offence gravity</li></ul><p>A skilled <a href="/services/bail-lawyer" style="color:var(--accent)">bail lawyer in Dhaka</a> argues for a lower bond amount the court will accept.</p>` },
            { h2: 'Lawyer Fees for Bail in Bangladesh', content: `<p>Bail lawyer fees in Bangladesh are not fixed by law — they are negotiated. Approximate market ranges:</p><ul><li><strong>Magistrate Court bail</strong>: BDT 5,000 – BDT 30,000 per application</li><li><strong>Sessions Court bail (non-bailable)</strong>: BDT 20,000 – BDT 1,00,000</li><li><strong>High Court Division bail</strong>: BDT 50,000 – BDT 5,00,000+ depending on seniority of advocate</li></ul><p>Urgent same-day filings and complex cases with multiple hearings cost more. Always agree on fee structure in writing beforehand. <a href="/" style="color:var(--accent)">Contact Advocate Md. Shah Alam</a> in Uttara for a realistic discussion.</p>` },
            { h2: 'Factors That Affect Bail Cost', content: `<p>What makes bail more expensive:</p><ul><li><strong>Severity of offence</strong>: Murder, rape, narcotics cases require senior High Court lawyers</li><li><strong>Number of accused</strong>: Cases with multiple co-accused are more complex</li><li><strong>Prior criminal record</strong>: Harder to argue for bail, more work for lawyer</li><li><strong>Strength of prosecution case</strong>: A weak case is easier to argue; weak applications need more preparation</li><li><strong>Urgency</strong>: Same-day emergency filings attract higher fees</li><li><strong>Advocate seniority</strong>: Senior Supreme Court advocates charge more than junior counsel</li></ul>` },
        ],
        faqs: [
            { question: 'Is bail refundable in Bangladesh?', answer: 'The lawyer\'s fee is not refundable. The bail bond/surety amount is security — not payment — and is returned at the end of the case provided the accused appeared at all hearings.' },
            { question: 'What is a surety in a Bangladesh bail application?', answer: 'A surety is a person who undertakes to pay the bond amount if the accused fails to appear in court. The surety must typically have immovable property within jurisdiction, and may be required to produce title documents.' },
            { question: 'Can I get bail the same day as arrest in Bangladesh?', answer: 'For bailable offences, yes — police can grant bail immediately. For non-bailable offences, an emergency application can be filed and heard as quickly as the same day or next day in urgent circumstances.' },
            { question: 'Can family members pay bail on behalf of the accused?', answer: 'Yes. Family members can act as surety or pay the lawyer\'s fees on behalf of the accused. The accused does not need to be present for the bail application to be filed.' },
        ],
        relatedServiceLinks: [
            { text: 'Bail Lawyer Dhaka', to: '/services/bail-lawyer' },
            { text: 'Criminal Lawyer Uttara', to: '/services/criminal-lawyer' },
            { text: 'Supreme Court Lawyer', to: '/services/supreme-court-lawyer' },
        ],
    },

    /* ── NEW 10 ── */
    {
        slug: 'tenant-landlord-dispute-bangladesh',
        bnSlug: 'bhara-tikki-bibad-bangladesh',
        title: 'Tenant and Landlord Disputes: Legal Rights in Bangladesh',
        category: 'Civil Law',
        readTime: '7 min read',
        metaTitle: 'Tenant Landlord Dispute Bangladesh – Legal Rights & Remedies 2025',
        metaDescription: 'Landlord refusing to return deposit? Tenant refusing to vacate? Know your rights under Bangladesh tenancy law — eviction process, rent disputes, and how to take legal action.',
        keywords: ['tenant landlord dispute Bangladesh', 'eviction law Bangladesh', 'rent dispute Bangladesh', 'house rent act Bangladesh', 'property lawyer Dhaka'],
        publishedDate: '2026-03-24',
        heroIntro: 'Tenant-landlord disputes are among the most common civil disputes in urban Bangladesh, particularly in Dhaka and Uttara. Both landlords and tenants have legal rights and obligations. Knowing them — and enforcing them correctly — makes all the difference.',
        toc: ['Tenancy Law in Bangladesh', "Tenant's Rights", "Landlord's Rights", 'How to Evict a Tenant Legally', 'Recovering Security Deposit', 'Taking Legal Action'],
        sections: [
            { h2: 'Tenancy Law in Bangladesh', content: `<p>Tenancy in urban Bangladesh is primarily governed by the <strong>House Rent Control Act 1991 (HRCA)</strong> and the <strong>Non-Agricultural Tenancy Act 1949</strong>. The HRCA applies to rental properties in designated urban areas and regulates rent increases, eviction grounds, and dispute mechanisms. The Rent Controller — a government officer — has special powers to adjudicate rent and eviction disputes without going to civil court.</p>` },
            { h2: "Tenant's Rights", content: `<p>Under Bangladesh tenancy law, as a tenant you have the right to:</p><ul><li>Written tenancy agreement or receipt acknowledging rent payment</li><li>Quiet enjoyment of the property without interference by the landlord</li><li>Return of security deposit (advance) within a reasonable time after vacating</li><li>Proper notice before eviction — typically 1–3 months depending on agreement and HRCA</li><li>Protection from illegal lock-outs or forcible eviction without court order</li><li>Complain to the Rent Controller if the landlord raises rent beyond legal limits</li></ul>` },
            { h2: "Landlord's Rights", content: `<p>A landlord's rights include:</p><ul><li>Receive rent on time as agreed in the tenancy deed</li><li>Recover possession after the tenancy period ends with proper notice</li><li>File an eviction case in Rent Controller Court or civil court for non-payment, misuse of property, or breach of agreement</li><li>Deduct from security deposit for verified damage beyond normal wear</li><li>Not renew a tenancy — provided proper notice is given per the agreement or law</li></ul>` },
            { h2: 'How to Evict a Tenant Legally', content: `<p>You cannot forcibly evict a tenant in Bangladesh — illegal eviction (disconnecting utilities, changing locks) exposes the landlord to criminal complaints. Legal eviction steps:</p><ol><li>Give proper written notice to vacate (typically 1 month for monthly tenancy).</li><li>If tenant refuses, file an eviction petition before the <strong>Rent Controller</strong> (urban areas) or a civil court.</li><li>Attend hearings — court will examine the grounds of eviction.</li><li>On a Court order, the tenant must vacate. Court bailiff enforces if needed.</li></ol><p>A <a href="/services/criminal-lawyer" style="color:var(--accent)">civil lawyer in Dhaka</a> can assist with the entire eviction process.</p>` },
            { h2: 'Recovering Security Deposit', content: `<p>If a landlord refuses to return the security deposit (advance rent):</p><ul><li>Send a legal notice through a lawyer demanding return within 30 days.</li><li>File a money recovery suit in a civil court for the deposit plus interest.</li><li>Alternatively, file a complaint before the Rent Controller who has jurisdiction over advance rent disputes.</li></ul><p><a href="/" style="color:var(--accent)">Contact Advocate Md. Shah Alam</a> for help with any tenant or landlord dispute in Dhaka or Uttara.</p>` },
        ],
        faqs: [
            { question: 'Can a landlord increase rent arbitrarily in Bangladesh?', answer: 'No. Under the House Rent Control Act 1991, rent increases in urban areas must comply with prescribed limits. Any dispute over illegal rent increase can be filed before the Rent Controller.' },
            { question: 'What if the landlord changes the lock while I still have belongings inside?', answer: 'This is an illegal eviction. File a police complaint for criminal trespass and simultaneously apply to the Rent Controller or civil court for an order restoring your possession.' },
            { question: 'Is a verbal tenancy agreement valid in Bangladesh?', answer: 'A verbal agreement is legally recognised but very difficult to enforce due to lack of written evidence. Always insist on a written Baidhok Patra (tenancy agreement) to protect your rights.' },
            { question: 'How long does an eviction case take in Bangladesh?', answer: 'Rent Controller proceedings can take 6 months to 2 years. Civil court eviction suits may take longer. An experienced lawyer can accelerate the process through correct procedure and persistent follow-up.' },
        ],
        relatedServiceLinks: [
            { text: 'Land & Property Lawyer', to: '/services/land-lawyer' },
            { text: 'Criminal Lawyer Dhaka', to: '/services/criminal-lawyer' },
        ],
    },

    /* ── NEW 11 ── */
    {
        slug: 'police-complaint-harassment-bangladesh',
        bnSlug: 'police-abiyog-hoirani-bangladesh',
        title: 'How to File a Police Complaint for Harassment in Bangladesh',
        category: 'Legal Procedures',
        readTime: '6 min read',
        metaTitle: 'How to File a Police Complaint for Harassment in Bangladesh',
        metaDescription: 'Being harassed in Bangladesh? Learn how to file a police GD or FIR for harassment — eve-teasing, workplace harassment, stalking, domestic abuse — step by step guide.',
        keywords: ['police complaint Bangladesh', 'file FIR harassment Bangladesh', 'GD complaint Bangladesh', 'harassment law Bangladesh', 'how to complain police Dhaka'],
        publishedDate: '2026-03-24',
        heroIntro: 'Knowing how to file a police complaint correctly in Bangladesh can protect you from harassment, stalking, workplace abuse, or domestic violence. This guide walks you through the process, documents needed, and what to do if police refuse to act.',
        toc: ['GD vs FIR: What is the Difference?', 'Step-by-Step: Filing a Complaint', 'Types of Harassment You Can File Against', 'What If Police Refuse to Take Your Complaint?', 'Role of a Lawyer in Harassment Cases'],
        sections: [
            { h2: 'GD vs FIR: What is the Difference?', content: `<p>Two types of police records are available:</p><ul><li><strong>GD (General Diary)</strong>: A record of an incident or complaint at the station level. Less formal, no automatic investigation begins. Use for minor incidents or to create an official record.</li><li><strong>FIR (First Information Report)</strong>: Filed for cognizable offences — police must investigate. Triggers a formal criminal case. FIR is what starts a prosecution.</li></ul><p>For serious harassment (physical assault, sexual harassment under Section 509 Penal Code, domestic violence), file an FIR. For milder incidents you want documented, a GD is appropriate.</p>` },
            { h2: 'Step-by-Step: Filing a Complaint', content: `<ol><li><strong>Visit the nearest police station</strong> in your area (thana).</li><li>Ask to speak to the Officer-in-Charge (OC).</li><li>Provide a written complaint (ejahar) describing the incident: date, time, place, accused person's name/description, what happened, witnesses.</li><li>The officer must enter the FIR in the station register and give you a copy with the GD/FIR number.</li><li>Obtain the FIR copy — you are legally entitled to it.</li><li>If the accused is known, police should arrest and investigate.</li></ol><p>Always keep a photocopy of your written complaint and the FIR number. <a href="/" style="color:var(--accent)">Contact Advocate Md. Shah Alam</a> if you need help drafting the ejahar.</p>` },
            { h2: 'What If Police Refuse to Take Your Complaint?', content: `<p>Police refusal to register an FIR is common in Bangladesh. Your options:</p><ul><li><strong>Approach the Superintendent of Police (SP)</strong> of the district — file a written complaint there.</li><li><strong>File a complaint directly in court</strong>: Under Section 190 CrPC, any Magistrate can take cognizance of an offence directly based on your complaint, bypassing police.</li><li><strong>File a writ petition</strong> in the High Court Division directing police to register your FIR.</li></ul><p>A lawyer can draft the court complaint or writ petition on your behalf.</p>` },
            { h2: 'Types of Harassment You Can File Against', content: `<p>Specific offences for harassment cases:</p><ul><li><strong>Eve-teasing / street harassment</strong>: Sections 76, 509 Penal Code; also Women & Children Repression Prevention Act 2000</li><li><strong>Sexual harassment at workplace</strong>: High Court guidelines 2009, Section 509 Penal Code</li><li><strong>Domestic violence/physical abuse</strong>: Domestic Violence (Prevention & Protection) Act 2010; Sections 323, 326, 498A Penal Code</li><li><strong>Online harassment / cyber bullying</strong>: Cyber Security Act 2023</li><li><strong>Stalking</strong>: Section 354D Penal Code (as amended)</li></ul>` },
        ],
        faqs: [
            { question: 'Can I file an FIR against an unknown person?', answer: 'Yes. The FIR can describe the unknown accused by physical description. Police will investigate and identify them.' },
            { question: 'Is a lawyer necessary to file a police complaint in Bangladesh?', answer: 'Not legally required, but having a lawyer draft your ejahar ensures all key facts are included, the correct legal provisions are cited, and the complaint is taken seriously by police.' },
            { question: 'How long does police have to investigate after an FIR?', answer: 'Police must submit a charge sheet or final report within 60–120 days (depending on the offence). Delays can be challenged in court.' },
            { question: 'Can I file a complaint against a police officer for misconduct?', answer: 'Yes. File a complaint with the Police Headquarters or the Independent Police Oversight Authority (IPOA). You can also file a writ petition in the High Court.' },
        ],
        relatedServiceLinks: [
            { text: 'Criminal Lawyer Uttara', to: '/services/criminal-lawyer' },
            { text: 'Bail Lawyer Dhaka', to: '/services/bail-lawyer' },
            { text: 'Divorce & Family Lawyer', to: '/services/divorce-lawyer' },
        ],
    },

    /* ── NEW 12 ── */
    {
        slug: 'succession-certificate-process-bangladesh',
        bnSlug: 'uttaradhikar-certificate-bangladesh',
        title: 'How to Get a Succession Certificate in Bangladesh',
        category: 'Civil Law',
        readTime: '7 min read',
        metaTitle: 'Succession Certificate Bangladesh – Process, Documents & Costs 2025',
        metaDescription: 'How to obtain a succession certificate in Bangladesh after someone dies — court process, required documents, timeline, costs, and how a civil lawyer can help.',
        keywords: ['succession certificate Bangladesh', 'succession certificate Dhaka', 'legal heir certificate Bangladesh', 'probate Bangladesh', 'civil lawyer Dhaka'],
        publishedDate: '2026-03-24',
        heroIntro: 'When a person dies in Bangladesh, banks and financial institutions often require a succession certificate before releasing assets to heirs. This legal document, granted by a civil court, confirms who the legal successors are and authorises them to receive money, shares, or debts owed to the deceased.',
        toc: ['What is a Succession Certificate?', 'When Do You Need One?', 'Which Court Grants It?', 'Step-by-Step Application Process', 'Required Documents', 'Timeline and Costs'],
        sections: [
            { h2: 'What is a Succession Certificate?', content: `<p>A succession certificate is a court order granted under the <strong>Succession Act 1925</strong> authorising specified heirs to receive movable assets of a deceased person — bank deposits, shares, savings certificates, pension dues, insurance proceeds, and debts payable to the deceased. It is different from a probate (which deals with wills and immovable property).</p>` },
            { h2: 'When Do You Need One?', content: `<p>You need a succession certificate when:</p><ul><li>A bank refuses to release the deceased's fixed deposits, savings, or current account balance without court authorisation</li><li>Collecting dividend or shares from a company where the deceased was a shareholder</li><li>Claiming life insurance proceeds from an insurer</li><li>Recovering outstanding salary, pension, or government dues</li><li>Recovering debts owed to the deceased by third parties</li></ul><p>If the deceased left a registered will, probate proceedings may be needed instead. A <a href="/services/criminal-lawyer" style="color:var(--accent)">civil lawyer in Dhaka</a> can advise which route applies.</p>` },
            { h2: 'Step-by-Step Application Process', content: `<ol><li><strong>File a petition</strong> in the District Judge Court or Civil Judge Court in the district where the deceased last ordinarily resided.</li><li>The petition states: deceased's details, relationship of applicant to deceased, list of all heirs, list of assets to be collected (with amounts), and prayer for certificate.</li><li>Court issues notice to all other legal heirs — they must be given an opportunity to object.</li><li>If no objections: court may grant the certificate without full trial.</li><li>If objections filed: full hearing and evidence presented.</li><li>Upon grant, the certificate specifies the heirs and their entitlement.</li><li>Present the certificate to the bank/institution to claim the assets.</li></ol>` },
            { h2: 'Required Documents', content: `<ul><li>Death certificate of the deceased (from hospital or Union Parishad)</li><li>NID of the applicant and all legal heirs</li><li>Proof of relationship (birth certificates, family certificate, kabinnama)</li><li>Bank statement or passbook showing the account balance</li><li>Share certificates or savings certificate copies (if applicable)</li><li>Two witnesses for the petition</li></ul>` },
            { h2: 'Timeline and Costs', content: `<p>Court fees are based on the value of assets claimed — typically 2–3% of the asset value (capped in some courts). An uncontested certificate can be obtained in <strong>2–4 months</strong>. A contested case with objections from other heirs may take 1–2 years. <a href="/" style="color:var(--accent)">Contact Advocate Md. Shah Alam</a> — a civil lawyer in Uttara — for fast, professional handling of your succession certificate case.</p>` },
        ],
        faqs: [
            { question: 'Can all heirs jointly apply for a succession certificate?', answer: 'Yes. A joint application by all known heirs is faster and less contentious than a single-heir application, which may face objections from other heirs.' },
            { question: 'Is a succession certificate required for land/property?', answer: 'No. For inheritance of land or immovable property, a mutation (namjari) application to the AC (Land) office is typically needed, not a succession certificate. Succession certificates cover movable assets and debts.' },
            { question: 'What if there are multiple heirs but one refuses to cooperate?', answer: 'You can still apply individually as one of the heirs. The court will notify all other heirs — non-cooperation by one does not prevent the certificate from being issued.' },
            { question: 'What is the difference between a succession certificate and a probate?', answer: 'A succession certificate covers movable property (money, debts, shares). Probate is granted by the High Court Division to authenticate a will and authorise the executor to deal with the deceased\'s estate — typically more relevant to large estates or immovable property.' },
        ],
        relatedServiceLinks: [
            { text: 'Land & Property Lawyer', to: '/services/land-lawyer' },
            { text: 'Supreme Court Lawyer', to: '/services/supreme-court-lawyer' },
        ],
    },

    /* ── NEW 13 ── */
    {
        slug: 'contract-breach-legal-action-bangladesh',
        bnSlug: 'chukti-bhanga-aini-poqdokkep-bangladesh',
        title: 'How to Take Legal Action for Contract Breach in Bangladesh',
        category: 'Civil Law',
        readTime: '7 min read',
        metaTitle: 'Contract Breach Legal Action Bangladesh – How to Sue for Breach 2025',
        metaDescription: 'Contract broken in Bangladesh? Know your legal remedies — damages, specific performance, injunction — and how to take legal action for breach of contract in Dhaka courts.',
        keywords: ['contract breach Bangladesh', 'breach of contract Bangladesh', 'sue for breach of contract Bangladesh', 'contract dispute Dhaka', 'civil lawyer Bangladesh'],
        publishedDate: '2026-03-24',
        heroIntro: 'Contract breaches are common in business — unpaid invoices, undelivered goods, broken construction contracts, and service agreement violations. Bangladesh contract law provides clear remedies, but enforcing them requires the right legal steps taken promptly.',
        toc: ['What Constitutes a Breach of Contract in Bangladesh?', 'Legal Remedies Available', 'Damages: Compensatory and Special', 'Specific Performance as a Remedy', 'How to File a Contract Dispute Case', 'How to Strengthen Your Contract Before Disputes Arise'],
        sections: [
            { h2: 'What Constitutes a Breach of Contract in Bangladesh?', content: `<p>Bangladesh contract law is governed by the <strong>Contract Act 1872</strong>. A breach occurs when a party without lawful excuse:</p><ul><li>Fails to perform an obligation when due (non-performance)</li><li>Performs defectively or partially</li><li>Anticipatorily repudiates the contract (indicates they will not perform before the due date)</li></ul><p>To pursue a remedy, the non-breaching party must show: (1) a valid contract existed; (2) the other party breached; (3) loss was caused by the breach.</p>` },
            { h2: 'Legal Remedies Available', content: `<p>Under the Contract Act and Specific Relief Act 1877, you can pursue:</p><ul><li><strong>Compensatory damages</strong>: Money to put you in the position you would have been in had the contract been performed.</li><li><strong>Special/consequential damages</strong>: If the breaching party knew of special circumstances at the time of contracting.</li><li><strong>Specific performance</strong>: Court orders the breaching party to perform. Available only when damages are an inadequate remedy (e.g., unique property, irreplaceable goods).</li><li><strong>Injunction</strong>: Prevents the breaching party from violating a contract term or doing an act contrary to the contract.</li><li><strong>Quantum meruit</strong>: Reasonable compensation for work done before the breach.</li></ul>` },
            { h2: 'How to File a Contract Dispute Case', content: `<ol><li><strong>Send a legal notice</strong> through a lawyer — gives the other party a chance to remedy the breach and is often required before filing suit.</li><li><strong>File a money suit or civil suit</strong> in the appropriate civil court (value determines court jurisdiction).</li><li>The trial court will hear evidence and witnesses.</li><li>Obtain a decree — a court order for payment of damages or specific performance.</li><li>Enforce the decree through execution proceedings (attachment of assets, bank accounts).</li></ol><p>A <a href="/services/criminal-lawyer" style="color:var(--accent)">civil litigation lawyer in Dhaka</a> can assess the strength of your claim and take prompt action.</p>` },
            { h2: 'How to Strengthen Your Contract Before Disputes Arise', content: `<p>Prevention is better than litigation:</p><ul><li>Always use a <strong>written, signed contract</strong> — verbal agreements are enforceable but hard to prove.</li><li>Include <strong>specific performance obligations</strong>, timelines, and payment terms.</li><li>Add a <strong>dispute resolution clause</strong>: arbitration or mediation before court.</li><li>Specify <strong>liquidated damages</strong> (pre-agreed compensation for breach) to avoid arguments over quantum.</li><li>Have contracts <strong>drafted or reviewed by a lawyer</strong> before signing.</li></ul><p><a href="/" style="color:var(--accent)">Advocate Md. Shah Alam</a> in Uttara handles commercial contract disputes and can draft agreements that protect your interests.</p>` },
        ],
        faqs: [
            { question: 'What is the limitation period for a contract breach case in Bangladesh?', answer: 'Under the Limitation Act 1908, the limitation period for a contract breach suit is 3 years from the date the breach occurred or the right to sue accrued. Do not delay.' },
            { question: 'Can I get an injunction to stop a breach from happening?', answer: 'Yes. If a breach is threatened or ongoing, apply for an urgent injunction in civil court to prevent it. This is particularly useful for exclusive contracts or property-related agreements.' },
            { question: 'Is arbitration faster than court litigation in Bangladesh?', answer: 'Generally yes. Arbitration under the Arbitration Act 2001 can resolve disputes in months rather than years, is private, and the award is enforceable like a court decree.' },
            { question: 'What if the breaching party has no assets?', answer: 'If the breaching party is insolvent, recovering a money decree becomes difficult. This is why financial due diligence before entering contracts with new parties is important.' },
        ],
        relatedServiceLinks: [
            { text: 'Company & Corporate Lawyer', to: '/services/company-corporate-lawyer' },
            { text: 'Supreme Court Lawyer', to: '/services/supreme-court-lawyer' },
            { text: 'Criminal Lawyer Dhaka', to: '/services/criminal-lawyer' },
        ],
    },

    /* ── NEW 14 ── */
    {
        slug: 'domestic-violence-legal-protection-bangladesh',
        bnSlug: 'gharelu-nirjaton-aini-suraksha-bangladesh',
        title: 'Domestic Violence: Legal Protection and Remedies in Bangladesh',
        category: 'Family Law',
        readTime: '7 min read',
        metaTitle: 'Domestic Violence Legal Protection Bangladesh – Rights & Remedies 2025',
        metaDescription: 'Experiencing domestic violence in Bangladesh? Know your legal rights under the Domestic Violence Act 2010 — protection orders, shelter, maintenance, and how to take legal action.',
        keywords: ['domestic violence Bangladesh', 'domestic violence law Bangladesh', 'protection order Bangladesh', 'DV Act 2010 Bangladesh', 'family lawyer Dhaka'],
        publishedDate: '2026-03-24',
        heroIntro: 'Domestic violence is a recognised legal harm in Bangladesh under the Domestic Violence (Prevention and Protection) Act 2010. Victims — primarily women and children — have access to immediate legal protection through court orders, shelter homes, and criminal prosecution of abusers.',
        toc: ['What is Domestic Violence Under Bangladesh Law?', 'Who is Protected?', 'Types of Protection Orders', 'How to Apply for a Protection Order', 'Criminal Complaints Alongside Civil Orders', 'Key Government Helplines and Resources'],
        sections: [
            { h2: 'What is Domestic Violence Under Bangladesh Law?', content: `<p>The Domestic Violence (Prevention and Protection) Act 2010 defines domestic violence broadly to include:</p><ul><li><strong>Physical abuse</strong>: Any act of bodily harm, assault, or use of force</li><li><strong>Sexual abuse</strong>: Forced sexual acts within marriage or the household</li><li><strong>Emotional/psychological abuse</strong>: Threats, humiliation, isolation, controlling behaviour</li><li><strong>Economic abuse</strong>: Withholding money, preventing employment, controlling assets</li></ul><p>Both ongoing relationships and post-separation situations are covered. A <a href="/services/divorce-lawyer" style="color:var(--accent)">family lawyer in Uttara</a> can assess your situation and recommend the fastest legal route.</p>` },
            { h2: 'Who is Protected?', content: `<p>The Act protects:</p><ul><li>Wife or former wife</li><li>Female partner in a live-in relationship</li><li>Female family members of the household</li><li>Children of the household</li></ul><p>Male victims of domestic violence can still seek remedies under the Penal Code (assault, grievous hurt) even though the DV Act 2010 primarily protects women and children.</p>` },
            { h2: 'Types of Protection Orders', content: `<p>A court can issue:</p><ul><li><strong>Protection Order</strong>: Prevents the abuser from committing further violence, contacting, or approaching the victim</li><li><strong>Residence Order</strong>: Prevents the abuser from entering the shared home or allows the victim to remain in the home</li><li><strong>Monetary Relief Order</strong>: Requires the abuser to pay for medical expenses, loss of earnings, or maintenance</li><li><strong>Custody Order</strong>: Temporary custody of children to the victim pending full hearing</li><li><strong>Compensation Order</strong>: Payment for pain, suffering, and emotional distress</li></ul>` },
            { h2: 'How to Apply for a Protection Order', content: `<ol><li><strong>File an application</strong> before the Chief Metropolitan Magistrate (in cities) or the Chief Judicial Magistrate (in districts) — or the Family Court.</li><li>Alternatively, report to a <strong>Protection Officer</strong> (government-appointed officer under the DV Act) who will assist in filing.</li><li>The court can issue an <strong>emergency or ex-parte order</strong> on the same day if there is imminent danger — without hearing the other side first.</li><li>Final hearing with both parties — court makes the permanent order.</li></ol><p>Evidence to gather: medical reports, photos of injuries, witness statements, WhatsApp/call records showing threats.</p>` },
            { h2: 'Criminal Complaints Alongside Civil Orders', content: `<p>Civil protection orders and criminal prosecution can run simultaneously. File an FIR at the police station for:</p><ul><li>Section 323/325 Penal Code: causing hurt or grievous hurt</li><li>Section 498A Penal Code: cruelty by husband or relatives</li><li>Women and Children Repression Prevention Act 2000: physical or sexual violence against women</li></ul><p>Criminal prosecution leads to imprisonment of the abuser, while civil orders provide immediate protection and financial relief. Use both pathways for maximum protection. <a href="/" style="color:var(--accent)">Contact Advocate Md. Shah Alam</a> for urgent legal help.</p>` },
        ],
        faqs: [
            { question: 'Can I get a protection order without a lawyer in Bangladesh?', answer: 'Yes. You can directly approach the Protection Officer or the Magistrate Court. However, a lawyer significantly improves your chances of getting an emergency same-day order and ensures all evidence is properly presented.' },
            { question: 'What emergency helplines are available for domestic violence victims in Bangladesh?', answer: 'National Emergency: 999 | Women and Children Helpline: 109 | Bangladesh National Women Lawyers\' Association (BNWLA): 01711-037893 | One-Stop Crisis Centres (OCC) at district hospitals provide free medical, legal, and shelter assistance.' },
            { question: 'Can I file a domestic violence case if I have already left the shared home?', answer: 'Yes. You can file for protection orders, maintenance, and criminal prosecution even after leaving the shared household. The Act still applies to past incidents and ongoing threats.' },
            { question: 'Will a protection order prevent my husband from seeing our children?', answer: 'Not automatically. A temporary custody order can be included in the protection order application. The court will balance the children\'s welfare with both parents\' access rights.' },
        ],
        relatedServiceLinks: [
            { text: 'Divorce & Family Lawyer', to: '/services/divorce-lawyer' },
            { text: 'Criminal Lawyer Uttara', to: '/services/criminal-lawyer' },
            { text: 'Supreme Court Lawyer', to: '/services/supreme-court-lawyer' },
        ],
    },

    /* ── NEW 15 ── */
    {
        slug: 'company-director-liability-bangladesh',
        bnSlug: 'company-director-dayitto-bangladesh',
        title: "Company Director Liability in Bangladesh: What You Need to Know",
        category: 'Company & Corporate Law',
        readTime: '7 min read',
        metaTitle: 'Company Director Liability Bangladesh – Personal & Legal Risks 2025',
        metaDescription: 'Are you a company director in Bangladesh? Know when you can be personally liable for company debts, fraud, tax defaults, and legal violations under the Companies Act 1994.',
        keywords: ['company director liability Bangladesh', 'director personal liability Bangladesh', 'Companies Act 1994 Bangladesh', 'corporate lawyer Dhaka', 'director responsibilities Bangladesh'],
        publishedDate: '2026-03-24',
        heroIntro: 'Many people assume that being a director of a limited liability company fully protects them from personal liability. In Bangladesh, this is not always true. Directors can face personal liability for fraud, tax defaults, environmental violations, and specific statutory duties — knowing these rules is essential for every company director.',
        toc: ['Limited Liability: The Basic Rule', 'When Directors Lose Protection: Personal Liability', 'Tax Liability of Directors', 'Director Duties Under the Companies Act 1994', 'Liability After Company Winding Up', 'How a Corporate Lawyer Can Help'],
        sections: [
            { h2: 'Limited Liability: The Basic Rule', content: `<p>In a private or public limited company, shareholders and directors generally enjoy <strong>limited liability</strong> — meaning their personal assets are protected from company debts. If the company cannot pay its debts, creditors can only look to the company's assets, not the personal property of directors. This is the "corporate veil."</p><p>However, Bangladesh law provides several situations where this veil is "lifted" and directors face personal responsibility.</p>` },
            { h2: 'When Directors Lose Protection: Personal Liability', content: `<p>Under the <strong>Companies Act 1994</strong> and general law, directors can be personally liable when:</p><ul><li><strong>Fraudulent trading</strong>: Directors knowingly carried on business to defraud creditors — personal liability for all company debts (Section 303 Companies Act)</li><li><strong>Wrongful trading</strong>: Directors continued trading when they knew or should have known the company could not pay its debts</li><li><strong>Breach of fiduciary duty</strong>: Acting in own interest rather than company's interest, accepting secret profits</li><li><strong>Ultra vires acts</strong>: Entering transactions beyond the company's Memorandum of Association</li><li><strong>Failure to maintain statutory registers</strong>: Personal fines apply</li><li><strong>Guarantee given personally</strong>: Bank loans secured by director personal guarantee make the director directly liable</li></ul>` },
            { h2: 'Tax Liability of Directors', content: `<p>The <strong>Income Tax Act 2023</strong> (and previous IT Ordinance 1984) hold directors jointly and severally liable for the company's tax arrears in certain circumstances, including:</p><ul><li>Where the company has insufficient assets to meet tax demands</li><li>Where the director was responsible for the conduct of the company's affairs</li><li>Where the tax remained unpaid due to the director's negligence or misfeasance</li></ul><p>Contact a <a href="/services/tax-lawyer" style="color:var(--accent)">tax lawyer in Dhaka</a> if you receive a tax recovery notice as a director for company tax dues.</p>` },
            { h2: 'Director Duties Under the Companies Act 1994', content: `<p>Every director in Bangladesh has statutory duties including:</p><ul><li>Act in good faith and in the best interests of the company</li>  <li>Exercise reasonable care, skill, and diligence</li><li>Avoid conflicts of interest</li><li>Not accept benefits from third parties</li><li>Disclose any personal interest in transactions</li><li>Maintain proper books of accounts</li><li>File annual returns with RJSC on time</li><li>Not trade while insolvent</li></ul><p>Breach of these duties can result in civil claims by the company or shareholders, and criminal prosecution in cases of fraud.</p>` },
            { h2: 'How a Corporate Lawyer Can Help', content: `<p>If you are a director facing:</p><ul><li>A creditor lawsuit claiming personal liability</li><li>A tax recovery notice for company arrears</li><li>A shareholder derivative suit for breach of duty</li><li>A winding-up petition where officers may be examined</li><li>A criminal complaint for company fraud</li></ul><p>An experienced <a href="/services/company-corporate-lawyer" style="color:var(--accent)">corporate lawyer in Dhaka</a> can assess your exposure, advise on defences, and represent you before the High Court Company Division, Tax Appellate Tribunal, or criminal courts. <a href="/" style="color:var(--accent)">Contact Advocate Md. Shah Alam</a> in Uttara for expert corporate law advice.</p>` },
        ],
        faqs: [
            { question: 'Can a director be arrested for company debts in Bangladesh?', answer: 'Not purely for civil debts. However, if fraud, tax evasion, or criminal breach of trust is alleged, criminal proceedings and arrest are possible. Civil debt alone does not lead to director arrest in most cases.' },
            { question: 'Is a nominee director also liable?', answer: 'Yes. Nominee directors (people appointed just for registration purposes) are still legally directors and share the same statutory liabilities. "Silent" director status is not a defence.' },
            { question: 'Can a director resign to avoid liability?', answer: 'Resignation after the fact does not protect a director from liability for acts committed during the directorship. Courts look at the period when the relevant act/omission occurred.' },
            { question: 'What is a director\'s indemnity insurance?', answer: 'Directors and Officers (D&O) liability insurance protects directors from personal financial loss due to claims of wrongful acts. It is increasingly common in larger Bangladesh companies. Consult a lawyer about whether it suits your company.' },
        ],
        relatedServiceLinks: [
            { text: 'Company & Corporate Lawyer', to: '/services/company-corporate-lawyer' },
            { text: 'Tax & VAT Lawyer', to: '/services/tax-lawyer' },
            { text: 'Supreme Court Lawyer', to: '/services/supreme-court-lawyer' },
        ],
    },


];